apiVersion: v1
kind: Service
metadata:
  name: pixelforge-studio
spec:
  ports:
  - port: 7860
    targetPort: 7860
    protocol: TCP
  selector:
    app: pixelforge-studio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelforge-studio
  labels:
    app: pixelforge-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixelforge-studio
  template:
    metadata:
      labels:
        app: pixelforge-studio
    spec:
      containers:
      - name: app
        image: modelscope-registry.cn-beijing.cr.aliyuncs.com/modelscope-repo/python:3.10
        ports:
        - containerPort: 7860
        env:
        - name: PORT
          value: "7860"
        volumeMounts:
        - name: app-storage
          mountPath: /home/user/app
        workingDir: /home/user/app
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: app-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi